# Ansible playbook to install Node Exporter, Prometheus, and Grafana

- hosts: all
  become: true
  tasks:
    - name: Install Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present
