version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://3.145.38.220:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "temperature_readings:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: temperature-database
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  kafka-consumer:
    build: ubuntu/kafka-consumer
    depends_on:
      - kafka
      - db
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_NAME: temperature_readings
      DB_HOST: 3.140.185.87
      DB_NAME: temperature-database
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}

